[settings]
activate_aggressive = true
experimental = true
lockfile = true
minimum_release_age = "0"

[tools]
actionlint = "1"
hk = "2"
pkl = "0"
shellcheck = "0"
shfmt = "3"
swift = "6"
swiftlint = "0"
yamlfmt = "0"
zizmor = "1"

[hooks]
postinstall = 'mise run bootstrap'

# tasks

[tasks.bootstrap]
run = [{ task = "_bootstrap_hk" }, "swift package resolve", "mise lock"]

[tasks.upd]
alias = ["update"]
run = ["mise upgrade", "swift package update"]

[tasks.upg]
alias = ["upgrade"]
run = ["mise upgrade --bump", "swift package update"]

[tasks.build]
alias = "b"
run = "swift build"

[tasks.test]
alias = "t"
run = "swift test"

[tasks.run]
alias = ["r", "xclint"]
run = "swift run xclint"

[tasks.check]
alias = ["lint", "chk"]
run = "hk check --all"

[tasks.fix]
alias = ["format"]
run = "hk fix --all"

[tasks.clean]
run = ["swift package clean", "swift package reset"]

[tasks.nuke]
depends = ["clean"]
run = "swift package purge-cache"

# Hidden Tasks

[tasks._bootstrap_hk]
hide = true
run = ["hk install --mise", "scripts/update-hk-import.bash"]
sources = ["hk.pkl", "mise.lock", "mise.toml", "scripts/update-hk-import.bash"]
outputs = { auto = true }
