[settings]
activate_aggressive = true
experimental = true

[tools]
actionlint = "1"
hk = "1"
pkl = "0"
shellcheck = "0"
shfmt = "3"
swift = "6"
swiftlint = "0"
yamlfmt = "0"
zizmor = "1"

[hooks]
postinstall = 'test -n "$CI" || mise run bootstrap'

# tasks

[tasks.bootstrap]
alias = "up"
run = [
  "mise install",
  "hk install --mise",
  { task = "update-hk-import" },
  "swift package resolve",
]

[tasks.update]
alias = ["upd"]
run = ["mise upgrade", { task = "update-hk-import" }, "swift package update"]

[tasks.upgrade]
alias = ["upg"]
run = [
  "mise upgrade --bump",
  { task = "update-hk-import" },
  "swift package update",
]

[tasks.update-hk-import]
run = "scripts/update-hk-import.bash"

[tasks.build]
alias = "b"
run = "swift build"

[tasks.test]
alias = "t"
run = "swift test"

[tasks.run]
alias = ["r", "xclint"]
run = "swift run xclint"

[tasks.package-release]
run = "scripts/package-release.bash"

[tasks.check]
alias = ["lint", "chk"]
run = "hk check --all"

[tasks.fix]
alias = ["format"]
run = "hk fix --all"

[tasks.clean]
run = ["swift package clean", "swift package reset"]

[tasks.nuke]
depends = ["clean"]
run = "swift package purge-cache"
