[settings]
activate_aggressive = true
experimental = true

[tools]
actionlint = "latest"
hk = "latest"
pkl = "latest"
shellcheck = "latest"
shfmt = "latest"
swift = "6.3"
yamlfmt = "latest"
zizmor = "latest"

[hooks]
postinstall = "mise run bootstrap"

# tasks

[tasks.bootstrap]
alias = "up"
run = [
  "mise install",
  "hk install --mise",
  { task = "update-hk-import" },
  "swift package resolve",
]

[tasks.update]
alias = ["upd"]
run = ["mise upgrade", { task = "update-hk-import" }, "swift package update"]

[tasks.upgrade]
alias = ["upg"]
run = [
  "mise upgrade --bump",
  { task = "update-hk-import" },
  "swift package update",
]

[tasks.update-hk-import]
run = "scripts/update-hk-import.bash"

[tasks.build]
alias = "b"
run = "swift build"

[tasks.test]
alias = "t"
run = "swift test"

[tasks.run]
alias = ["r", "xclint"]
run = "swift run xclint"

[tasks.check]
alias = ["lint", "chk"]
run = "mise fmt --check"

[tasks.fix]
alias = ["format"]
run = "mise fmt"

[tasks.clean]
run = ["swift package clean", "swift package reset"]

[tasks.nuke]
depends = ["clean"]
run = "swift package purge-cache"
