name: Homebrew Install

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - run: brew tap hisaac/XCLint "$GITHUB_WORKSPACE"
      - run: brew install xclint
      - run: .github/scripts/verify-version.sh
